### ISSUE TITLE
Error while starting Plugin instance

### ISSUE THREAD

**Issue by abhisheksharma2805** [Kong/kong-python-pdk#15]
I was trying to run the `py-hello` plugin. I have added all configuration correctly in kong.conf file to enable the plugin and start the python server. But when I make a request to the service for which the plugin is enabled it throws the following error. 
```
[info] 24#0: *11 [python:30] INFO - [17:14:58] instance #1 of py-hello started, context: ngx.timer
[info] 24#0: *11 [python:30] ERROR - [17:14:58] rpc: #5 exception: Traceback (most recent call last):, context: ngx.timer
[info] 24#0: *11 [python:30]   File "/usr/lib/python3.8/site-packages/kong_pdk/listener.py", line 61, in handle, context: ngx.timer
[info] 24#0: *11 [python:30]     ret = getattr(self.ps, cmd_r)(*args), context: ngx.timer
[info] 24#0: *11 [python:30]   File "/usr/lib/python3.8/site-packages/kong_pdk/server.py", line 50, in wrapper, context: ngx.timer
[info] 24#0: *11 [python:30]     raise(ex), context: ngx.timer
[info] 24#0: *11 [python:30]   File "/usr/lib/python3.8/site-packages/kong_pdk/server.py", line 47, in wrapper, context: ngx.timer
[info] 24#0: *11 [python:30]     r = fn(*args, **kwargs), context: ngx.timer
[info] 24#0: *11 [python:30]   File "/usr/lib/python3.8/site-packages/kong_pdk/server.py", line 263, in close_instance, context: ngx.timer
[info] 24#0: *11 [python:30]     "Name": ins['name'],, context: ngx.timer
[info] 24#0: *11 [python:30] TypeError: 'Instance' object is not subscriptable, context: ngx.timer


[error] 25#0: *12721 [kong] mp_rpc.lua:308 [py-hello] no data, client: 172.19.0.1, server: kong, request: "GET /my-app HTTP/1.1", host: "localhost:8000"
```

**Comment by abhisheksharma2805** [comment]
Somehow I am not getting this error now after resolving some other issues I were facing. Closing this for now. Will raise this issue if I encounter this in future
