### ISSUE TITLE
Error while building python-pdk from source tar.gz

### ISSUE THREAD

**Issue by rohan-97** [Kong/kong-python-pdk#7]
Hi Guys,

I wanted to install/build python-pdk from source package instead of installing it using python-pip

I went to official python pypi website
https://pypi.org/project/kong-pdk/#files

and downloaded the tar.gz file 
Following is the link of tar.gz file
https://files.pythonhosted.org/packages/1c/f4/b376c00b465b2cec71ad53578035c6f38c802c7ef9f609baa4bbb61c63b6/kong_pdk-0.23.tar.gz

following files were present in the tarball

```
root@geek:/tmp/kong_pdk-0.23# tar tvf ../kong_pdk-0.23.tar.gz
drwxr-xr-x fffonion/staff    0 2021-05-13 05:17 kong_pdk-0.23/
-rw-r--r-- fffonion/staff 11345 2021-03-22 03:08 kong_pdk-0.23/LICENSE
-rw-r--r-- fffonion/staff  7426 2021-05-13 05:17 kong_pdk-0.23/PKG-INFO
-rw-r--r-- fffonion/staff  2928 2021-02-24 04:27 kong_pdk-0.23/README.md
drwxr-xr-x fffonion/staff     0 2021-05-13 05:17 kong_pdk-0.23/kong_pdk/
-rw-r--r-- fffonion/staff     0 2021-03-26 04:39 kong_pdk-0.23/kong_pdk/__init__.py
-rw-r--r-- fffonion/staff  4791 2021-05-13 05:15 kong_pdk-0.23/kong_pdk/cli.py
-rw-r--r-- fffonion/staff   671 2021-05-13 05:16 kong_pdk-0.23/kong_pdk/const.py
-rw-r--r-- fffonion/staff    89 2021-03-26 04:39 kong_pdk-0.23/kong_pdk/exception.py
-rw-r--r-- fffonion/staff    22 2021-03-26 04:39 kong_pdk-0.23/kong_pdk/kong.py
-rw-r--r-- fffonion/staff  3514 2021-05-13 05:15 kong_pdk-0.23/kong_pdk/listener.py
-rw-r--r-- fffonion/staff  5579 2021-03-26 04:39 kong_pdk-0.23/kong_pdk/logger.py
-rw-r--r-- fffonion/staff  2694 2021-05-13 05:15 kong_pdk-0.23/kong_pdk/module.py
drwxr-xr-x fffonion/staff     0 2021-05-13 05:17 kong_pdk-0.23/kong_pdk/pdk/
-rw-r--r-- fffonion/staff   720 2021-03-29 06:11 kong_pdk-0.23/kong_pdk/pdk/__init__.py
-rw-r--r-- fffonion/staff 10403 2021-05-13 05:15 kong_pdk-0.23/kong_pdk/server.py
drwxr-xr-x fffonion/staff     0 2021-05-13 05:17 kong_pdk-0.23/kong_pdk.egg-info/
-rw-r--r-- fffonion/staff  7426 2021-05-13 05:17 kong_pdk-0.23/kong_pdk.egg-info/PKG-INFO
-rw-r--r-- fffonion/staff   448 2021-05-13 05:17 kong_pdk-0.23/kong_pdk.egg-info/SOURCES.txt
-rw-r--r-- fffonion/staff     1 2021-05-13 05:17 kong_pdk-0.23/kong_pdk.egg-info/dependency_links.txt
-rw-r--r-- fffonion/staff    72 2021-05-13 05:17 kong_pdk-0.23/kong_pdk.egg-info/entry_points.txt
-rw-r--r-- fffonion/staff     1 2021-03-26 04:39 kong_pdk-0.23/kong_pdk.egg-info/not-zip-safe
-rw-r--r-- fffonion/staff    15 2021-05-13 05:17 kong_pdk-0.23/kong_pdk.egg-info/requires.txt
-rw-r--r-- fffonion/staff   137 2021-05-13 05:17 kong_pdk-0.23/kong_pdk.egg-info/top_level.txt
-rw-r--r-- fffonion/staff    38 2021-05-13 05:17 kong_pdk-0.23/setup.cfg
-rw-r--r-- fffonion/staff  1916 2021-03-29 06:15 kong_pdk-0.23/setup.py
```
After extracting tar file,
I tried to build kong-pdk using following command

```
python3 setup.py build
```
and I got following error
```
root@geek:/tmp/kong_pdk-0.23# python3 setup.py build
setup.py:8: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import os, json, imp
/usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'license_files'
  warnings.warn(msg)
Warning: 'classifiers' should be a list, got type 'tuple'
running build
running build_py
creating build
creating build/lib
creating build/lib/kong_pdk
copying kong_pdk/server.py -> build/lib/kong_pdk
copying kong_pdk/cli.py -> build/lib/kong_pdk
copying kong_pdk/module.py -> build/lib/kong_pdk
copying kong_pdk/kong.py -> build/lib/kong_pdk
copying kong_pdk/listener.py -> build/lib/kong_pdk
copying kong_pdk/const.py -> build/lib/kong_pdk
copying kong_pdk/logger.py -> build/lib/kong_pdk
copying kong_pdk/exception.py -> build/lib/kong_pdk
copying kong_pdk/__init__.py -> build/lib/kong_pdk
creating build/lib/kong_pdk/pdk
copying kong_pdk/pdk/__init__.py -> build/lib/kong_pdk/pdk
error: package directory 'kong_pdk/pdk/kong' does not exist
```
also following is the error in installing the package

```
root@geek:/tmp/kong_pdk-0.23# python3 setup.py install
setup.py:8: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import os, json, imp
/usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'license_files'
  warnings.warn(msg)
Warning: 'classifiers' should be a list, got type 'tuple'
running install
running bdist_egg
running egg_info
writing kong_pdk.egg-info/PKG-INFO
writing dependency_links to kong_pdk.egg-info/dependency_links.txt
writing entry points to kong_pdk.egg-info/entry_points.txt
writing requirements to kong_pdk.egg-info/requires.txt
writing top-level names to kong_pdk.egg-info/top_level.txt
error: package directory 'kong_pdk/pdk/kong' does not exist
```
Just wanted to confirm am I following correct approach?
also is there any other way to compile and install kong-python-pdk from tar file as we wanted to avoid introducing python-pip in system

Thanks!

**Comment by fffonion** [comment]
Hmmm looks like tar archive is missing some files, try install use the `.egg` file (it's just an zip archive).

I'll see what's missing to build the tar.gz file.

**Comment by rohan-97** [comment]
Hi @fffonion ,

I downloaded the .whl file and tried to compaire the files with those in tar.gz file

I found following difference

Following is the file contents of whl file
```
root@protegrity-framework492:~/kong-pdk/zipped# tree kong_pdk
kong_pdk
├── cli.py
├── const.py
├── exception.py
├── __init__.py
├── kong.py
├── listener.py
├── logger.py
├── module.py
├── pdk
│   ├── __init__.py
│   ├── kong
│   │   ├── client
│   │   │   └── tls.pyi
│   │   ├── client.pyi
│   │   ├── cluster.pyi
│   │   ├── ctx
│   │   │   └── shared.pyi
│   │   ├── ctx.pyi
│   │   ├── ip.pyi
│   │   ├── log.pyi
│   │   ├── nginx
│   │   │   └── shared.pyi
│   │   ├── nginx.pyi
│   │   ├── node.pyi
│   │   ├── request.pyi
│   │   ├── response.pyi
│   │   ├── router.pyi
│   │   ├── service
│   │   │   ├── request.pyi
│   │   │   └── response.pyi
│   │   ├── service.pyi
│   │   └── table.pyi
│   └── kong.pyi
└── server.py
```

and following is the file content of tar.gz file
```
kong_pdk-0.23/
├── kong_pdk
│   ├── cli.py
│   ├── const.py
│   ├── exception.py
│   ├── __init__.py
│   ├── kong.py
│   ├── listener.py
│   ├── logger.py
│   ├── module.py
│   ├── pdk
│   │   └── __init__.py
│   └── server.py
├── kong_pdk.egg-info
│   ├── dependency_links.txt
│   ├── entry_points.txt
│   ├── not-zip-safe
│   ├── PKG-INFO
│   ├── requires.txt
│   ├── SOURCES.txt
│   └── top_level.txt
├── LICENSE
├── PKG-INFO
├── README.md
├── setup.cfg
└── setup.py
```
So looks like tar.gz file is missing kong directory and kong.pyi file

**Comment by rohan-97** [comment]
I copied the kong directory and kong.pyi into files extracted by tar.gz file.

and tried to install the package and got following error

```
setup.py:8: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import os, json, imp
/usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'license_files'
  warnings.warn(msg)
Warning: 'classifiers' should be a list, got type 'tuple'
running install
running bdist_egg
running egg_info
writing kong_pdk.egg-info/PKG-INFO
writing dependency_links to kong_pdk.egg-info/dependency_links.txt
writing entry points to kong_pdk.egg-info/entry_points.txt
writing requirements to kong_pdk.egg-info/requires.txt
writing top-level names to kong_pdk.egg-info/top_level.txt
package init file 'kong_pdk/pdk/kong/__init__.py' not found (or not a regular file)
package init file 'kong_pdk/pdk/kong/client/__init__.py' not found (or not a regular file)
package init file 'kong_pdk/pdk/kong/ctx/__init__.py' not found (or not a regular file)
package init file 'kong_pdk/pdk/kong/nginx/__init__.py' not found (or not a regular file)
package init file 'kong_pdk/pdk/kong/service/__init__.py' not found (or not a regular file)
reading manifest file 'kong_pdk.egg-info/SOURCES.txt'
writing manifest file 'kong_pdk.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/kong_pdk
copying kong_pdk/__init__.py -> build/lib/kong_pdk
copying kong_pdk/logger.py -> build/lib/kong_pdk
copying kong_pdk/const.py -> build/lib/kong_pdk
copying kong_pdk/kong.py -> build/lib/kong_pdk
copying kong_pdk/server.py -> build/lib/kong_pdk
copying kong_pdk/exception.py -> build/lib/kong_pdk
copying kong_pdk/listener.py -> build/lib/kong_pdk
copying kong_pdk/cli.py -> build/lib/kong_pdk
copying kong_pdk/module.py -> build/lib/kong_pdk
creating build/lib/kong_pdk/pdk
copying kong_pdk/pdk/__init__.py -> build/lib/kong_pdk/pdk
copying kong_pdk/pdk/kong.pyi -> build/lib/kong_pdk/pdk
creating build/lib/kong_pdk/pdk/kong
copying kong_pdk/pdk/kong/nginx.pyi -> build/lib/kong_pdk/pdk/kong
copying kong_pdk/pdk/kong/ip.pyi -> build/lib/kong_pdk/pdk/kong
copying kong_pdk/pdk/kong/client.pyi -> build/lib/kong_pdk/pdk/kong
copying kong_pdk/pdk/kong/service.pyi -> build/lib/kong_pdk/pdk/kong
copying kong_pdk/pdk/kong/table.pyi -> build/lib/kong_pdk/pdk/kong
copying kong_pdk/pdk/kong/router.pyi -> build/lib/kong_pdk/pdk/kong
copying kong_pdk/pdk/kong/node.pyi -> build/lib/kong_pdk/pdk/kong
copying kong_pdk/pdk/kong/response.pyi -> build/lib/kong_pdk/pdk/kong
copying kong_pdk/pdk/kong/request.pyi -> build/lib/kong_pdk/pdk/kong
copying kong_pdk/pdk/kong/cluster.pyi -> build/lib/kong_pdk/pdk/kong
copying kong_pdk/pdk/kong/log.pyi -> build/lib/kong_pdk/pdk/kong
copying kong_pdk/pdk/kong/ctx.pyi -> build/lib/kong_pdk/pdk/kong
creating build/lib/kong_pdk/pdk/kong/ctx
copying kong_pdk/pdk/kong/ctx/shared.pyi -> build/lib/kong_pdk/pdk/kong/ctx
creating build/lib/kong_pdk/pdk/kong/service
copying kong_pdk/pdk/kong/service/response.pyi -> build/lib/kong_pdk/pdk/kong/service
copying kong_pdk/pdk/kong/service/request.pyi -> build/lib/kong_pdk/pdk/kong/service
creating build/lib/kong_pdk/pdk/kong/client
copying kong_pdk/pdk/kong/client/tls.pyi -> build/lib/kong_pdk/pdk/kong/client
creating build/lib/kong_pdk/pdk/kong/nginx
copying kong_pdk/pdk/kong/nginx/shared.pyi -> build/lib/kong_pdk/pdk/kong/nginx
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/kong_pdk
copying build/lib/kong_pdk/__init__.py -> build/bdist.linux-x86_64/egg/kong_pdk
copying build/lib/kong_pdk/logger.py -> build/bdist.linux-x86_64/egg/kong_pdk
copying build/lib/kong_pdk/const.py -> build/bdist.linux-x86_64/egg/kong_pdk
copying build/lib/kong_pdk/kong.py -> build/bdist.linux-x86_64/egg/kong_pdk
copying build/lib/kong_pdk/server.py -> build/bdist.linux-x86_64/egg/kong_pdk
copying build/lib/kong_pdk/exception.py -> build/bdist.linux-x86_64/egg/kong_pdk
copying build/lib/kong_pdk/listener.py -> build/bdist.linux-x86_64/egg/kong_pdk
creating build/bdist.linux-x86_64/egg/kong_pdk/pdk
copying build/lib/kong_pdk/pdk/__init__.py -> build/bdist.linux-x86_64/egg/kong_pdk/pdk
copying build/lib/kong_pdk/pdk/kong.pyi -> build/bdist.linux-x86_64/egg/kong_pdk/pdk
creating build/bdist.linux-x86_64/egg/kong_pdk/pdk/kong
creating build/bdist.linux-x86_64/egg/kong_pdk/pdk/kong/ctx
copying build/lib/kong_pdk/pdk/kong/ctx/shared.pyi -> build/bdist.linux-x86_64/egg/kong_pdk/pdk/kong/ctx
copying build/lib/kong_pdk/pdk/kong/nginx.pyi -> build/bdist.linux-x86_64/egg/kong_pdk/pdk/kong
creating build/bdist.linux-x86_64/egg/kong_pdk/pdk/kong/service
copying build/lib/kong_pdk/pdk/kong/service/response.pyi -> build/bdist.linux-x86_64/egg/kong_pdk/pdk/kong/service
copying build/lib/kong_pdk/pdk/kong/service/request.pyi -> build/bdist.linux-x86_64/egg/kong_pdk/pdk/kong/service
copying build/lib/kong_pdk/pdk/kong/ip.pyi -> build/bdist.linux-x86_64/egg/kong_pdk/pdk/kong
copying build/lib/kong_pdk/pdk/kong/client.pyi -> build/bdist.linux-x86_64/egg/kong_pdk/pdk/kong
copying build/lib/kong_pdk/pdk/kong/service.pyi -> build/bdist.linux-x86_64/egg/kong_pdk/pdk/kong
copying build/lib/kong_pdk/pdk/kong/table.pyi -> build/bdist.linux-x86_64/egg/kong_pdk/pdk/kong
copying build/lib/kong_pdk/pdk/kong/router.pyi -> build/bdist.linux-x86_64/egg/kong_pdk/pdk/kong
copying build/lib/kong_pdk/pdk/kong/node.pyi -> build/bdist.linux-x86_64/egg/kong_pdk/pdk/kong
creating build/bdist.linux-x86_64/egg/kong_pdk/pdk/kong/client
copying build/lib/kong_pdk/pdk/kong/client/tls.pyi -> build/bdist.linux-x86_64/egg/kong_pdk/pdk/kong/client
copying build/lib/kong_pdk/pdk/kong/response.pyi -> build/bdist.linux-x86_64/egg/kong_pdk/pdk/kong
copying build/lib/kong_pdk/pdk/kong/request.pyi -> build/bdist.linux-x86_64/egg/kong_pdk/pdk/kong
copying build/lib/kong_pdk/pdk/kong/cluster.pyi -> build/bdist.linux-x86_64/egg/kong_pdk/pdk/kong
creating build/bdist.linux-x86_64/egg/kong_pdk/pdk/kong/nginx
copying build/lib/kong_pdk/pdk/kong/nginx/shared.pyi -> build/bdist.linux-x86_64/egg/kong_pdk/pdk/kong/nginx
copying build/lib/kong_pdk/pdk/kong/log.pyi -> build/bdist.linux-x86_64/egg/kong_pdk/pdk/kong
copying build/lib/kong_pdk/pdk/kong/ctx.pyi -> build/bdist.linux-x86_64/egg/kong_pdk/pdk/kong
copying build/lib/kong_pdk/cli.py -> build/bdist.linux-x86_64/egg/kong_pdk
copying build/lib/kong_pdk/module.py -> build/bdist.linux-x86_64/egg/kong_pdk
byte-compiling build/bdist.linux-x86_64/egg/kong_pdk/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/kong_pdk/logger.py to logger.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/kong_pdk/const.py to const.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/kong_pdk/kong.py to kong.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/kong_pdk/server.py to server.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/kong_pdk/exception.py to exception.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/kong_pdk/listener.py to listener.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/kong_pdk/pdk/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/kong_pdk/cli.py to cli.cpython-37.pyc
byte-compiling build/bdist.linux-x86_64/egg/kong_pdk/module.py to module.cpython-37.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying kong_pdk.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying kong_pdk.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying kong_pdk.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying kong_pdk.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying kong_pdk.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying kong_pdk.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying kong_pdk.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating dist
creating 'dist/kong_pdk-0.23-py3.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing kong_pdk-0.23-py3.7.egg
removing '/usr/local/lib/python3.7/dist-packages/kong_pdk-0.23-py3.7.egg' (and everything under it)
creating /usr/local/lib/python3.7/dist-packages/kong_pdk-0.23-py3.7.egg
Extracting kong_pdk-0.23-py3.7.egg to /usr/local/lib/python3.7/dist-packages
kong-pdk 0.23 is already the active version in easy-install.pth
Installing kong-python-pluginserver script to /usr/local/bin

Installed /usr/local/lib/python3.7/dist-packages/kong_pdk-0.23-py3.7.egg
Processing dependencies for kong-pdk==0.23
Searching for gevent
Reading https://pypi.org/simple/gevent/
Downloading https://files.pythonhosted.org/packages/0b/50/1b1175ea3a269b5fa3f0f7fed11149888180695bef5fbf568adbb196efaf/gevent-21.1.2.tar.gz#sha256=520cc2a029a9eef436e4e56b007af7859315cafa21937d43c1d5269f12f2c981
Best match: gevent 21.1.2
Processing gevent-21.1.2.tar.gz
Writing /tmp/easy_install-l7rddqhi/gevent-21.1.2/setup.cfg
Running gevent-21.1.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-l7rddqhi/gevent-21.1.2/egg-dist-tmp-pj0n70pw
warning: no files found matching 'changelog.rst'
warning: no files found matching 'Makefile.ext'
warning: no files found matching 'known_failures.py'
warning: no files found matching '.pep8'
no previously-included directories found matching '*/__pycache__'
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no previously-included files matching '*.o' found anywhere in distribution
warning: no previously-included files matching '*.lo' found anywhere in distribution
warning: no previously-included files matching '*.la' found anywhere in distribution
warning: no previously-included files matching '.dirstamp' found anywhere in distribution
warning: no previously-included files matching 'config.log' found anywhere in distribution
warning: no previously-included files matching 'config.status' found anywhere in distribution
warning: no previously-included files matching 'config.cache' found anywhere in distribution
no previously-included directories found matching 'docs/_build'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '.coverage' found under directory 'src/greentest'
no previously-included directories found matching 'src/greentest/htmlcov'
warning: no previously-included files matching 'stamp-h?' found under directory 'deps/c-ares'
warning: no previously-included files matching 'ares_build.h.orig' found under directory 'deps/c-ares'
warning: no previously-included files matching '_corecffi.c' found under directory 'src/gevent'
warning: no previously-included files found matching 'configure-output'
warning: no previously-included files found matching 'configure-output.txt'
warning: no previously-included files found matching 'deps/TAGS'
warning: no previously-included files found matching 'deps/c-ares/ares_build.h'
warning: no previously-included files found matching 'deps/c-ares/ares_config.h'
warning: no previously-included files found matching 'deps/c-ares/libcares.pc'
warning: no previously-included files found matching 'deps/c-ares/libtool'
warning: no previously-included files found matching 'deps/c-ares/Makefile'
no previously-included directories found matching 'deps/c-ares/.deps'
no previously-included directories found matching 'deps/c-ares/.libs'
no previously-included directories found matching 'deps/libev/.deps'
no previously-included directories found matching 'deps/libev/.libs'
warning: no previously-included files matching 'Makefile' found under directory 'deps/libev'
warning: no previously-included files matching 'libtool' found under directory 'deps/libev'
warning: no previously-included files matching 'stamp-h?' found under directory 'deps/libev'
warning: no previously-included files matching 'config.h' found under directory 'deps/libev'
no previously-included directories found matching 'deps/libuv/.deps'
no previously-included directories found matching 'deps/libuv/.libs'
no previously-included directories found matching 'deps/libuv/src/.deps'
no previously-included directories found matching 'deps/libuv/src/unix/.deps'
no previously-included directories found matching 'deps/libuv/src/win/.deps'
no previously-included directories found matching 'deps/libuv/test/.deps'
no previously-included directories found matching 'deps/libuv/autom4te.cache'
no previously-included directories found matching 'deps/libuv/m4'
warning: no previously-included files matching 'Makefile' found under directory 'deps/libuv'
warning: no previously-included files matching 'Makefile.in' found under directory 'deps/libuv'
warning: no previously-included files matching 'ar-lib' found under directory 'deps/libuv'
warning: no previously-included files matching 'aclocal.m4' found under directory 'deps/libuv'
warning: no previously-included files matching 'compile' found under directory 'deps/libuv'
warning: no previously-included files matching 'configure' found under directory 'deps/libuv'
warning: no previously-included files matching 'depcomp' found under directory 'deps/libuv'
warning: no previously-included files matching 'install-sh' found under directory 'deps/libuv'
warning: no previously-included files matching 'libtool' found under directory 'deps/libuv'
warning: no previously-included files matching 'libuv.pc' found under directory 'deps/libuv'
warning: no previously-included files matching 'ltmain.sh' found under directory 'deps/libuv'
warning: no previously-included files matching 'missing' found under directory 'deps/libuv'
Running '(cd  "/tmp/easy_install-l7rddqhi/gevent-21.1.2/deps/libev"  && sh ./configure -C > configure-output.txt )' in /tmp/easy_install-l7rddqhi/gevent-21.1.2
configure: error: in `/tmp/easy_install-l7rddqhi/gevent-21.1.2/deps/libev':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-l7rddqhi/gevent-21.1.2/setup.py", line 479, in <module>
  File "/tmp/easy_install-l7rddqhi/gevent-21.1.2/setup.py", line 463, in run_setup
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 24, in run
    self.build()
  File "/usr/lib/python3.7/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_ext')
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/cffi/setuptools_ext.py", line 141, in run
    ext.sources[0] = make_mod(self.build_temp, pre_run)
  File "/usr/lib/python3/dist-packages/cffi/setuptools_ext.py", line 126, in make_mod
    pre_run(ext, ffi)
  File "/tmp/easy_install-l7rddqhi/gevent-21.1.2/_setuputils.py", line 364, in pre_run
  File "/tmp/easy_install-l7rddqhi/gevent-21.1.2/_setuplibev.py", line 55, in configure_libev
  File "/tmp/easy_install-l7rddqhi/gevent-21.1.2/_setuputils.py", line 195, in system
  File "/tmp/easy_install-l7rddqhi/gevent-21.1.2/_setuputils.py", line 191, in _system
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '(cd  "/tmp/easy_install-l7rddqhi/gevent-21.1.2/deps/libev"  && sh ./configure -C > configure-output.txt )' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 62, in <module>
    package_data={"kong_pdk": ["*.pyi", "**/*.pyi", "**/**/*.pyi", "**/**/**/*.pyi"]}
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 443, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 685, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 732, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 777, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 704, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 730, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 915, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1183, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1169, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/lib/python3/dist-packages/setuptools/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-l7rddqhi/gevent-21.1.2/setup.py", line 479, in <module>
  File "/tmp/easy_install-l7rddqhi/gevent-21.1.2/setup.py", line 463, in run_setup
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 24, in run
    self.build()
  File "/usr/lib/python3.7/distutils/command/install_lib.py", line 109, in build
    self.run_command('build_ext')
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/cffi/setuptools_ext.py", line 141, in run
    ext.sources[0] = make_mod(self.build_temp, pre_run)
  File "/usr/lib/python3/dist-packages/cffi/setuptools_ext.py", line 126, in make_mod
    pre_run(ext, ffi)
  File "/tmp/easy_install-l7rddqhi/gevent-21.1.2/_setuputils.py", line 364, in pre_run
  File "/tmp/easy_install-l7rddqhi/gevent-21.1.2/_setuplibev.py", line 55, in configure_libev
  File "/tmp/easy_install-l7rddqhi/gevent-21.1.2/_setuputils.py", line 195, in system
  File "/tmp/easy_install-l7rddqhi/gevent-21.1.2/_setuputils.py", line 191, in _system
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '(cd  "/tmp/easy_install-l7rddqhi/gevent-21.1.2/deps/libev"  && sh ./configure -C > configure-output.txt )' returned non-zero exit status 1.
```

**Comment by rohan-97** [comment]
Am I missing some package/dependency??

**Comment by fffonion** [comment]
`configure: error: cannot run C compiled programs.`
you need a build toolchain

**Comment by fffonion** [comment]
Closing as the issue seems be environment related. Please re-open if the issue persists.
